services:
  nginx:
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt:/etc/letsencrypt
      - ./html:/usr/share/nginx/html
      - ./ip:/usr/share/nginx/ip
      - ./gamerecords:/usr/share/nginx/gamerecords
      - ./anybet:/usr/share/nginx/anybet
      - ./anycoin:/usr/share/nginx/anycoin
      - ./ardu:/usr/share/nginx/ardu
      - ./it-startup:/usr/share/nginx/it-startup
      - ./site1:/usr/share/nginx/html/site1
      - ./site2:/usr/share/nginx/html/site2
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped
    networks:
      - sharednetwork

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;'"
    networks:
      - sharednetwork

networks:
  sharednetwork:
    external: true