services:
  ardua:
    build: .
    working_dir: /app2
    ports:
      - "3003:3000"
    volumes:
      - .:/app2
    command: sh -c "yarn install && yarn prisma generate && concurrently \"yarn dev\" \"ts-node server.ts\""
    env_file:
      - .env
    networks:
      - sharednetwork
    restart: always

networks:
  sharednetwork:
    external: true