services:
  ardua:
    build: .
    working_dir: /app2
    ports:
      - "3003:3000"
      - "8085:8085"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    networks:
      - sharednetwork
    restart: always

networks:
  sharednetwork:
    external: true