services:
  ardu1:
    build: .
    working_dir: /app2
    ports:
      - "3003:3000"
    volumes:
      - .:/app
    command: ["yarn", "start"]
    env_file:
      - .env
    networks:
      - sharednetwork
    restart: always

networks:
  sharednetwork:
    external: true